name: my first workflow

on: push
jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo "Hello, github actions"
            - name: Print name
              run: echo "Sanyam"
            - name: Print bye
              run: echo "bye github action"

    job2:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo "Hey, github actions"
            - name: Print name
              run: echo "Sanyam"
            - name: Print bye
              run: echo "bye bye github action"

            
