name: my first workflow

on: push
jobs:
    say-hello:
        runs-on: ubuntu-latest

        steps:
            - name: Print message
              run: echo "Hello, github actions"
            - name: Print name
              run: echo "Sanyam"
            - name: Print bye
              run: echo "bye github action"

            