name: my first workflow

on: push
jobs:
    job1:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses : action/checkout@v4
            - name: list file
              run: ls

    job2:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses : action/checkout@v4
            - name: list file
              run: ls

            
